const PDFDocument = require('pdfkit');

function generatePdf(session, discrepancies, documents, res) {
  const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=FinVerify_Report_${session.id}.pdf`);
  doc.pipe(res);

  // Colors
  const PRIMARY_COLOR = '#1e3a8a'; // Tailwind blue-900
  const TEXT_COLOR = '#334155'; // Tailwind slate-700
  const SECONDARY_COLOR = '#64748b'; // Tailwind slate-500
  const BORDER_COLOR = '#e2e8f0'; // Tailwind slate-200

  // Helper to strip markdown
  const stripMarkdown = (md) => {
    if (!md) return '';
    return md.replace(/(\*\*|__)(.*?)\1/g, '$2') // bold
             .replace(/(\*|_)(.*?)\1/g, '$2') // italic
             .replace(/#+\s/g, '') // headers
             .replace(/`{3}[\s\S]*?`{3}/g, '') // code blocks
             .replace(/`/g, ''); // inline code
  };

  // --- COVER PAGE ---
  doc.rect(0, 0, doc.page.width, 20).fill(PRIMARY_COLOR);
  
  doc.moveDown(5);
  doc.font('Helvetica-Bold').fontSize(28).fillColor(PRIMARY_COLOR).text('FINANCIAL DUE DILIGENCE', { align: 'center' });
  doc.font('Helvetica').fontSize(18).fillColor(SECONDARY_COLOR).text('Discrepancy & Readiness Report', { align: 'center' });
  
  doc.moveDown(4);
  doc.font('Helvetica-Bold').fontSize(14).fillColor(TEXT_COLOR).text('STRICTLY CONFIDENTIAL', { align: 'center' });
  
  doc.moveDown(2);
  doc.font('Helvetica').fontSize(12).fillColor(SECONDARY_COLOR);
  doc.text(`Generated by: FinVerify AI`, { align: 'center' });
  doc.text(`Date: ${new Date(session.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });
  doc.text(`Session Ref: ${session.id}`, { align: 'center' });
  doc.text(`Documents Analyzed: ${documents.length}`, { align: 'center' });
  
  doc.moveDown(2);
  doc.font('Helvetica-Bold').fontSize(14).fillColor(TEXT_COLOR).text(`Readiness Score: ${session.readiness_score}/100`, { align: 'center' });

  // --- PAGE 2: EXECUTIVE SUMMARY ---
  doc.addPage();
  doc.rect(0, 0, doc.page.width, 10).fill(PRIMARY_COLOR);
  doc.moveDown();
  
  doc.font('Helvetica-Bold').fontSize(18).fillColor(PRIMARY_COLOR).text('1. EXECUTIVE SUMMARY');
  doc.moveDown();
  
  const rawSummary = session.summary_report?.summary || 'No summary available.';
  const cleanSummary = stripMarkdown(rawSummary);
  
  doc.font('Helvetica').fontSize(11).fillColor(TEXT_COLOR).text(cleanSummary, { align: 'justify', lineGap: 4 });
  doc.moveDown(2);

  // --- PAGE 3: FINDINGS & METRICS ---
  doc.addPage();
  doc.rect(0, 0, doc.page.width, 10).fill(PRIMARY_COLOR);
  doc.moveDown();
  
  doc.font('Helvetica-Bold').fontSize(18).fillColor(PRIMARY_COLOR).text('2. FINDINGS OVERVIEW');
  doc.moveDown();
  
  doc.font('Helvetica').fontSize(12).fillColor(TEXT_COLOR);
  doc.text(`Verified Mismatches: ${session.total_mismatches}`);
  doc.text(`Missing Information: ${session.total_missing}`);
  doc.text(`Unusual Assumption Changes: ${session.total_unusual}`);
  doc.text(`Unresolved Inconsistencies: ${session.total_inconsistencies}`);
  doc.moveDown(2);

  doc.font('Helvetica-Bold').fontSize(18).fillColor(PRIMARY_COLOR).text('3. DETAILED DISCREPANCIES');
  doc.moveDown();
  
  if (!discrepancies || discrepancies.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor(TEXT_COLOR).text('No discrepancies found.');
  } else {
    discrepancies.forEach((d, i) => {
      // Draw a box for each discrepancy
      const startY = doc.y;
      doc.rect(50, startY, doc.page.width - 100, 110).stroke(BORDER_COLOR);
      
      doc.y = startY + 10;
      doc.x = 60;
      
      doc.font('Helvetica-Bold').fontSize(12).fillColor(PRIMARY_COLOR).text(`${d.ref_code}: ${d.metric_name}`);
      doc.font('Helvetica').fontSize(10).fillColor('#ef4444').text(`Classification: ${d.classification}`);
      if (d.variance_pct) {
        doc.fillColor(SECONDARY_COLOR).text(`Variance: ${d.variance_pct.toFixed(2)}%`);
      }
      
      doc.moveDown(0.5);
      doc.fillColor(TEXT_COLOR).text(`Description: ${d.description}`, { width: doc.page.width - 120 });
      
      doc.moveDown(0.5);
      doc.font('Helvetica-Oblique').fontSize(9).fillColor(SECONDARY_COLOR).text(`Suggested Question: ${d.follow_up_question || 'None'}`, { width: doc.page.width - 120 });
      
      doc.x = 50; // Reset X
      doc.y = startY + 130; // Move down for the next box
      
      if (doc.y > doc.page.height - 100) {
        doc.addPage();
        doc.rect(0, 0, doc.page.width, 10).fill(PRIMARY_COLOR);
        doc.moveDown();
      }
    });
  }

  // Footer on all pages
  let pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.font('Helvetica').fontSize(8).fillColor(SECONDARY_COLOR);
    doc.text(`FinVerify AI - Confidential - Page ${i + 1} of ${pages.count}`, 
      50, 
      doc.page.height - 30, 
      { align: 'center' }
    );
  }

  doc.end();
}

module.exports = { generatePdf };
